ANCHO = 21
ALTO = 13
COOLDOWN_MOVIMIENTO = 0.3
TIEMPO_EXPLOSION_BOMBA = 3.0

VACIO = 0
MURO_ACERO = 1
MURO_LADRILLO = 2
FUEGO = 3
BOMBA = 4

DICCIONARIO_SIMBOLOS = {
    VACIO: "⬜",
    MURO_ACERO: "🧱",
    MURO_LADRILLO: "📦",
    FUEGO: "💥",
    BOMBA: "💣"
}